### ISSUE TITLE
Adversary model of Secret Store

### ISSUE THREAD

**Issue by ErikP0** [paritytech/secret-store#43]
What is the adversary model that was used when implementing the secret store?

I wasn't able to find any information on that in the [wiki](https://wiki.parity.io/Secret-Store).

I'm specifically interested in whether it is tolerated that a subset of up to `t` secret store instances collude/are taken over by the adversary. Is arbitrary deviation from the protocol also tolerated?

**Comment by svyatonik** [comment]
Here are some assumptions:
1) key servers set is a privileged set, where nodes can't be added/removed without some administrative procedure (staking? running trusted builds? this is outside of current SS scope). The reason is that in our model any detected misbehavior during key generation, stops generation. So basically any key server from the set could just say "let's not generate key" => SS won't work as expected;
2) if misbehavior is detected, the key server/the subset/the whole set must be punished and eventually misbehaving key server(s) must be removed from the set;
3) misbehavior could be detected either by other key servers (if this is supported by the undelying protocol - e.g. node agrees to participate in decryption, but fail to provide share data), or by the SS client (e.g. `hash(decrypt(document_key, document)) != key_id` or `verify_signature(message, signature, server_public) == false`);
4) so speaking of misbehavior actions, they can be treated as:
4.1) benign - if misbehavior can be detected either by other nodes, or by client when key is requested;
4.2) malicious - if misbehavior can't be detected both by other nodes and by client.

Re your questions:
5) "whether it is tolerated that a subset of up to t secret store instances collude/are taken over by the adversary" - as long as there's no t+1 adversaries in the set, the private portion of server key (and plain document key) should not be revealed to anyone, but the valid requester;
6) "is arbitrary deviation from the protocol also tolerated" - if it's 4.1-like, then it is ok, else it should be considered fatal.

**Comment by ErikP0** [comment]
Ok, thanks a lot.
I will close this issue then.
